// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WpfApp3.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260203124251_Mig6")]
    partial class Mig6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WpfApp3.EF.Groups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("WpfApp3.EF.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("fullName")
                        .HasColumnType("text");

                    b.Property<int?>("groupId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("groupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("WpfApp3.EF.Subjects", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Cabinet")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("num")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("WpfApp3.EF.TableClasses.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WpfApp3.EF.TableClasses.GroupSubjects", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("Id")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("groupSubjects");
                });

            modelBuilder.Entity("WpfApp3.EF.TableClasses.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Cabinet")
                        .HasColumnType("text");

                    b.Property<string>("Day")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NumDay")
                        .HasColumnType("integer");

                    b.Property<int?>("Subjectsid")
                        .HasColumnType("integer");

                    b.Property<string>("group")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Subjectsid");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("WpfApp3.EF.Groups", b =>
                {
                    b.HasOne("WpfApp3.EF.TableClasses.Account", null)
                        .WithMany("Groups")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("WpfApp3.EF.Student", b =>
                {
                    b.HasOne("WpfApp3.EF.Groups", "group")
                        .WithMany("students")
                        .HasForeignKey("groupId");

                    b.Navigation("group");
                });

            modelBuilder.Entity("WpfApp3.EF.TableClasses.GroupSubjects", b =>
                {
                    b.HasOne("WpfApp3.EF.Groups", "Group")
                        .WithMany("GS")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WpfApp3.EF.Subjects", "Subject")
                        .WithMany("GS")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("WpfApp3.EF.TableClasses.Lesson", b =>
                {
                    b.HasOne("WpfApp3.EF.TableClasses.Account", null)
                        .WithMany("Lessons")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WpfApp3.EF.Subjects", null)
                        .WithMany("lessons")
                        .HasForeignKey("Subjectsid");
                });

            modelBuilder.Entity("WpfApp3.EF.Groups", b =>
                {
                    b.Navigation("GS");

                    b.Navigation("students");
                });

            modelBuilder.Entity("WpfApp3.EF.Subjects", b =>
                {
                    b.Navigation("GS");

                    b.Navigation("lessons");
                });

            modelBuilder.Entity("WpfApp3.EF.TableClasses.Account", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
